#andrew clavin
#feb 22 2016
#chapter 4 stuff for python class

'''4.1.19. Generalize the pond function further to allow for the pond to be
annually restocked with an additional quantity of fish.'''
def pond(years, growth, restock):
    """Simulates a fish population in a fishing pond, and
       prints annual population size. The population grows 8% per year
       with an annual harvest of 1500.

    Parameter:
        years: number of years to simulate

    Return value: the final population size
    """

    population = 12000
    for year in range(years):
        population = growth * population + restock - 1500
        print(year + 1, int(population))

    return population

'''4.3.1. Suppose you put $1000 into the bank and you get a 3%
interest rate compounded annually. How would you use a while
loop to determine how long will it take for your account to
have at least $1200 in it?'''
def checkRateOfGrowth(p_start, p_end):
    counter = 0
    while p_start < p_end:
        p_start *= 1.03
        counter += 1
        print(counter)
    return counter

'''Write a function that returns a list of letter grades
    corresponding to the numerical scores in the list scores.
    For example, computeGrades([78, 91, 85]) should return the
    list [‘C’, ‘A’, ‘B’]. To test your function, use lists of
    scores generated by the following function.
'''
def computeGrades(scores):
    grades = []
    for score in scores:
        if score >= 90:
            grades.append('A')
        elif score >= 80:
            grades.append('B')
        elif score >= 70:
            grades.append('C')
        elif score >= 60:
            grades.append('D')
        else:
            grades.append('F')
        
    return grades

'''5.4.9. Write a function
    that prompts for a grade, and then returns the corresponding
    remark (as a string) from the table below:
    Grade  | Remark
    96-100 | Outstanding
    90-95  | Exceeds expectations
    80-89  | Acceptable
    1-79   | Trollish
'''

def gradeRemark():
    grade = int(input("What's ya' grade?"))
    if grade >= 96:
        return "Outstanding"
    elif grade >= 90:
        return "Exceeds expectations"
    elif grade >= 80:
        return "Acceptable"
    elif grade >= 1:
        return "Trollish"


def main():
    finalPopulation = pond(10, 1.08, 6)
    print('The final population is', finalPopulation)
    print("""To grow money from 1000 bucks to 1200 at 3%
          annualy it would take""", checkRateOfGrowth(1000, 1200), 'years')
    print("Grades", computeGrades([78, 91, 85]))
    print(gradeRemark())

main()
